#bridge-file-version: #10
#bridge-file-version: #4
# Start the goblin army event
say A goblin army has arrived
summon terrariamod:goblinarmy_dummy
summon terrariamod:goblin_sorcerer
summon terrariamod:goblin_peon
summon terrariamod:goblin_thief
summon terrariamod:goblin_warrior
summon terrariamod:goblin_archer
summon terrariamod:goblin_sorcerer
summon terrariamod:goblin_peon
summon terrariamod:goblin_thief
summon terrariamod:goblin_warrior
summon terrariamod:goblin_archer
summon terrariamod:goblin_sorcerer
summon terrariamod:goblin_peon
summon terrariamod:goblin_thief
summon terrariamod:goblin_warrior
summon terrariamod:goblin_archer
summon terrariamod:goblin_sorcerer
summon terrariamod:goblin_peon
summon terrariamod:goblin_thief
summon terrariamod:goblin_warrior
summon terrariamod:goblin_archer
summon terrariamod:goblin_sorcerer
summon terrariamod:goblin_peon
summon terrariamod:goblin_thief
summon terrariamod:goblin_warrior
summon terrariamod:goblin_archer
summon terrariamod:goblin_sorcerer
summon terrariamod:goblin_peon
summon terrariamod:goblin_thief
summon terrariamod:goblin_warrior
summon terrariamod:goblin_archer
summon terrariamod:goblin_sorcerer
summon terrariamod:goblin_peon
summon terrariamod:goblin_thief
summon terrariamod:goblin_warrior
summon terrariamod:goblin_archer
 